server:
  port: 3333
spring:
  application:
    name:  activity-test
  redis:
    database: 5
    host: 192.168.1.106
    port: 6379
    password: linweili123
    timeout: 10ms
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://10.100.99.164:3306/jm?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456a
    slave:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://10.100.99.164:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456a
test:
  appname: 123456a
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://10.100.14.107:21111/eureka/
  instance:
    ip-address: 10.100.97.31
    prefer-ip-address: true
