server:
  port: 3333
spring:
  application:
    name:  activity-test
  redis:
    database: 5
    host: 192.168.1.106
    port: 6379
    password: linweili123
    timeout: 10ms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jm?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456a

mybatis:
  type-aliases-package: com.test.jm.dto
  mapper-locations: classpath:mappers/*.xml
test:
  appname: 123456a
#mybatis分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:1111//eureka/
  instance:
    ip-address: 192.168.1.106
    prefer-ip-address: true
