server:
  port: 3333
spring:
  application:
    name:  activity-test
  profiles:
  redis:
    database: 5
    host: node.td-k8s.com
    port: 1379
    password: mWRK6joVy5No
    timeout: 10ms
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.1.3:3306/jm?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456a
    slave:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.1.3:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
      username: root
      password: 123456a
test:
  appname: 123456a
#mybatis分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
#      defaultZone: http://10.100.14.107:21111//eureka/
      defaultZone: http://localhost:1111//eureka/
  instance:
    ip-address: 10.100.97.31
    prefer-ip-address: true
