server:
  port: 3333

spring:
  profiles:
    active: test
  application:
    name:  activity-test
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      name: activity-test
      profile: test
      fail-fast: true
      label: master

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    ip-address: 10.100.97.31
    prefer-ip-address: true
