server:
  port: 3333

spring:
  profiles:
    active: dev
  application:
    name:  activity-test
  cloud:
    config:
      discovery:
        service-id: config-server
        enabled: true
      name: activity-test
      profile: dev
      fail-fast: true
      label: master
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    ip-address: 10.100.97.31
    prefer-ip-address: true
